apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  labels:
    app.kubernetes.io/name: metallb
spec:
  project: default
  source:
    repoURL: https://metallb.github.io/metallb
    targetRevision: latest
    chart: metallb
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
