apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  labels:
    app.kubernetes.io/name: nginx
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: latest
    chart: nginx
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
