ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: argocd.pocket-kube.com
      paths:
        - /
  tls:
    - secretName: argocd-tls
      hosts:
        - argocd.pocket-kube.com
